### ISSUE TITLE
[Bug] Carrousel Items - Tap Actions Broken

### ISSUE THREAD

**Issue by eliasacab** [KieronQuinn/SmartspacerPlugins#16]
### Select the Plugin you are reporting for

Tasker

### Description

When using the carousel template and setting up multiple items, each with their own Tap Action ID, the ID of the last item (bottom) is sent whenever any of the items are tapped.
For example, tapping item 1 of the carrousel will send the ID of item 3 instead of 1. Thanks!

**Comment by KieronQuinn** [comment]
Unfortunately this is neither a plugin bug nor a Smartspacer bug, but a system bug. For some reason, the system is taking the each Carousel Tap Action and setting it for the whole carousel, rather than the item it's set for - and as the last one is set last, it's that one which is used. 

Smartspacer's implementation in the widget, Expanded Smartspace and Client SDK handles this properly, and does not have the issue. 

This is Google's problem to fix sadly.
