### ISSUE TITLE
[Plugin Request] Time to Home and Time to Work

### ISSUE THREAD

**Issue by sheikn** [KieronQuinn/SmartspacerPlugins#44]
### App / Plugin Name

Google Maps Traffic Plugin

### Description

The current Google Maps traffic plugin (as the name suggests) only displays traffic information. Would it be possible to display "Time to home" and "Time to work" at predefined times, like the Pixel phones do?

### Where will the plugin get data from?

Widget

### Requirements

- [X] I have read the requirements
- [X] The information I have provided is correct

**Comment by KieronQuinn** [comment]
I think At a Glance (either via Smartspace or the widget) already supports this doesn't it?

**Comment by sheikn** [comment]
Commute times now only get displayed on Pixels. I think they have been made Pixel exclusive as evidenced by the removal of the "Commute" settings on non Pixel devices [https://chromeunboxed.com/pixel-at-a-glance-commute](https://chromeunboxed.com/pixel-at-a-glance-commute) . However, the Google Distance Matrix api still allows retrieval of this information [https://developers.google.com/maps/documentation/distance-matrix/overview](https://developers.google.com/maps/documentation/distance-matrix/overview)

**Comment by KieronQuinn** [comment]
The AAG widget has support for commute time & time to leave on non-Pixels too. If the widget is not working for you, you may be able to use the notifications that appear on some devices with the same content (using the Notification Target), or you may need to contact Google because the widget does claim to support this functionality, and if it does show in the AAG widget it will show in Smartspacer.

Otherwise, that API is not free, in fact it would be _very_ expensive, so is not viable.
